"""Reporting helpers (LaTeX export of figures and tables, plots)."""

from my_project.reporting.latex_export import (
    format_latex_bold_best,
    latex_escape,
    results_latex_dir,
    save_figure,
    save_latex_table,
    save_table,
    slugify,
)
from my_project.reporting.plotting import (
    edge_jaccard_matrix,
    pair_table_from_matrix,
    pairwise_ii_mi_table,
    plot_category_barplots,
    plot_class_balance,
    plot_feature_histograms,
    plot_ii_by_edges,
    plot_ii_graph,
    top_k_edges,
)
from my_project.reporting.presentation import (
    CATEGORICAL_PALETTE,
    CATEGORY_LABELS_PL,
    GRAPH_LABELS,
    PLOT_LABELS_PL,
    SEQUENTIAL_PALETTE,
    configure_notebook_plots,
    graph_display_name,
    plot_label,
    uses_edge_count,
)

__all__ = [
    "CATEGORICAL_PALETTE",
    "CATEGORY_LABELS_PL",
    "GRAPH_LABELS",
    "PLOT_LABELS_PL",
    "SEQUENTIAL_PALETTE",
    "configure_notebook_plots",
    "edge_jaccard_matrix",
    "format_latex_bold_best",
    "graph_display_name",
    "latex_escape",
    "pair_table_from_matrix",
    "pairwise_ii_mi_table",
    "plot_category_barplots",
    "plot_class_balance",
    "plot_feature_histograms",
    "plot_ii_by_edges",
    "plot_ii_graph",
    "plot_label",
    "results_latex_dir",
    "save_figure",
    "save_latex_table",
    "save_table",
    "slugify",
    "top_k_edges",
    "uses_edge_count",
]
